version: '3.7'

services:
  python:
    image: rgrun/gymcrawler-python:latest
    build: ./collector/.
    container_name: datacrawler
    env_file: .env
    # restart: unless-stopped
    ports:
        - 3000:3000
    volumes:
        - ./collector/src/logs:/app/src/logs
    depends_on:
      - mongo
    command: 
      - /bin/sh
      - -c
      - |
        wait
        python3 collector.py
    networks:
      - python-mongo-net
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    ports:
        - 27017:27017
    volumes:
        - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        - ./mongo/data:/data/db
    networks:
      - python-mongo-net

networks:
  python-mongo-net:
    driver: bridge